### ISSUE TITLE
Unable to add a range

### ISSUE THREAD

**Issue by leguaan** [prsyahmi/BadMemory#3]
Whenever I try to add the addresses 1048c3018 - 10c8c4ff8 (4168.7 - 4296.7) I keep getting [FAIL] as a result (MemTest86+ gave me 001048c3018 & 0010c8c4ff8). I have installed the signed driver.

Any ideas?

![fail](https://user-images.githubusercontent.com/22646423/31342293-f6d116d0-ad14-11e7-84af-ebb5fe1523dd.PNG)

**Comment by leguaan** [comment]
I was able to solve this issue by disabling rank interleaving which changed the error address to around 2GB instead of 4GB, since it seemed like the beginning of 0x100000000 was in use by Windows for some reason.  After some trial & error I was able to lock down the range and verify that it actually did through RAMMap. Thanks for your extremely helpful program.
![fail](https://user-images.githubusercontent.com/22646423/31348268-be41c13a-ad27-11e7-9cbf-d7aa76128504.PNG)

**Comment by prsyahmi** [comment]
Hi, you are welcome. Windows/driver may use some of the higher address, so this solution is actually not a guaranteed reliable. The driver will start itself earliest possible and allocate the bad region, so no other driver/windows memory manager may allocate the bad region. If windows/something else had took up the bad region first it will FAIL.

Since I made this driver my PC still runs perfectly fine and survived windows updates. Needs to be cautious if you are running major updates, like from Win 10 Anniversary to Creators Update since windows will start another OS (WinPE) without the driver. It may end up causing you a boot loop.

I've may have forgot to mention ram interleaving in the readme, will update it soon. Thanks for using this software.
